module.exports=
[{concern:"11's"                 ,bodayParts:"Upper Face"                                                                     , treatments:[]},
{concern:"Acne"                  , bodayParts:"Arms,Back,Chest,Lower Face,Midface,Neck,Upper Face"                              , treatments:[]},
{concern:"Acne Scarring"         , bodayParts:"Arms,Back,Chest,Lower Face,Midface,Neck,Upper Face"                              , treatments:[]},
{concern:"Bags Under Eyes"       , bodayParts:"Upper Face"                                                                      , treatments:[]},
{concern:"Brown Spots"           , bodayParts:"Hands,Lower Face,Midface,Neck,Upper Face"                                        , treatments:[]},
{concern:"Cherry Angiomas"       , bodayParts:"Chest,Hands,Lower Face,Midface,Upper Face"                                       , treatments:[]},
{concern:"Clogged Pores"         , bodayParts:"Lower Face,Midface,Neck,Upper Face"                                              , treatments:[]},
{concern:"Combination Skin"      , bodayParts:"Lower Face,Midface,Neck,Upper Face"                                              , treatments:[]},
{concern:"Crepey, Aging Skin"    , bodayParts:"Hands,Lower Face,Midface,Neck,Upper Face"                                        , treatments:[]},
{concern:"Crows Feet"            , bodayParts:"Upper Face"                                                                      , treatments:[]},
{concern:"Dark Circles"          , bodayParts:"Midface,Upper Face"                                                              , treatments:[]},
{concern:"Double Chin"           , bodayParts:"Lower Face,Neck"                                                                 , treatments:[]},
{concern:"Drooping Forehead"     , bodayParts:"Upper Face"                                                                      , treatments:[]},
{concern:"Dry Skin"              , bodayParts:"Lower Face,Midface,Neck,Upper Face"                                              , treatments:[]},
{concern:"Excess Fat"            , bodayParts:"Abdomen,Arms,Back,Chest,Lower Face,Midface,Neck,Upper Face"                      , treatments:[]},
{concern:"Excess Hair"           , bodayParts:"Arms,Back,Buttocks,Chest,Intimate,Lower Face,Lower Legs,Thighs,Upper Face"       , treatments:[]},
{concern:"Facial Folds"          , bodayParts:"Lower Face,Midface,Upper Face"                                                   , treatments:[]},
{concern:"Fine Lines"            , bodayParts:"Lower Face,Midface,Neck,Upper Face"                                              , treatments:[]},
{concern:"Freckles"              , bodayParts:"Lower Face,Midface,Upper Face"                                                   , treatments:[]},
{concern:"Frown Lines"           , bodayParts:"Lower Face,Midface,Upper Face"                                                   , treatments:[]},
{concern:"Furrowed Brow"         , bodayParts:"Upper Face"                                                                      , treatments:[]},
{concern:"Hair"                  , bodayParts:"Midface"                                                                         , treatments:[]},
{concern:"Hyperpigmentation"     , bodayParts:"Lower Face,Midface,Neck,Upper Face"                                              , treatments:[]},
{concern:"Jowls Jawline"         , bodayParts:"Lower Face,Neck"                                                                 , treatments:[]},
{concern:"Large Pores"           , bodayParts:"Lower Face,Midface,Neck,Upper Face"                                              , treatments:[]},
{concern:"Lip Enhancement"       , bodayParts:"Lips"                                                                            , treatments:[]},
{concern:"Loose Skin"            , bodayParts:"Arms,Lower Face,Lower Legs,Midface,Neck,Thighs,Upper Face"                       , treatments:[]},
{concern:"Loss of Facial Volume" , bodayParts:"Lower Face,Midface,Upper Face"                                                   , treatments:[]},
{concern:"Melasma"               , bodayParts:"Lower Face,Midface,Neck,Upper Face"                                              , treatments:[]},
{concern:"Muffin Top"            , bodayParts:"Abdomen"                                                                         , treatments:[]},
{concern:"Nasolabial Folds"      , bodayParts:"Midface"                                                                         , treatments:[]},
{concern:"Oily Skin"             , bodayParts:"Lower Face,Midface,Neck,Upper Face"                                              , treatments:[]},
{concern:"Puffy Eyes"            , bodayParts:"Upper Face"                                                                      , treatments:[]},
{concern:"Red Spots"             , bodayParts:"Hands,Lower Face,Midface"                                                        , treatments:[]},
{concern:"Rosacea"               , bodayParts:"Lower Face,Midface,Neck,Upper Face"                                              , treatments:[]},
{concern:"Rough Skin"            , bodayParts:"Lips,Lower Face,Midface,Neck,Upper Face"                                         , treatments:[]},
{concern:"Sagging Eyelids"       , bodayParts:"Upper Face"                                                                      , treatments:[]},
{concern:"Sagging Skin"          , bodayParts:"Arms,Chest,Lower Face,Lower Legs,Midface,Neck,Thighs,Upper Face"                 , treatments:[]},
{concern:"Sensitive Skin"        , bodayParts:"Lips,Lower Face,Midface,Neck,Upper Face"                                         , treatments:[]},
{concern:"Sunspots"              , bodayParts:"Lower Face,Midface,Upper Face"                                                   , treatments:[]},
{concern:"Thin Lips"             , bodayParts:"Lips"                                                                            , treatments:[]},
{concern:"Undefined Cheekbones"  , bodayParts:"Midface"                                                                         , treatments:[]},
{concern:"Uneven Skin Texture"   , bodayParts:"Lips,Lower Face,Midface,Neck,Upper Face"                                         , treatments:[]},
{concern:"Uneven Skin Tone"      , bodayParts:"Lips,Lower Face,Midface,Neck,Upper Face"                                         , treatments:[]},
{concern:"Unwanted Hair"         , bodayParts:"Arms,Back,Chest,Intimate,Lower Face,Lower Legs,Midface,Thighs,Upper Face"        , treatments:[]},
{concern:"Wrinkles"              , bodayParts:"Arms,Chest,Hands,Lower Face,Midface,Neck,Upper Face"                             , treatments:[]}]